import "./style.css";
import { DOMEngine } from "./components/DOMEngine";
const DOM = new DOMEngine();
DOM.initialize();
DOM.createProjectObject("test", "tomorrow");
// DOM.createProjectObject("test", "next Week");
DOM.updateProjectsDOM();
// DOM.clearProjectsDOM();
// DOM.clearProjectsDOM();
// DOM.updateProjectsDOM();
